#!/bin/bash

projectName=kusama
projectChain=kusama

function portAssign {
port=$((10000 + $RANDOM % 100000))
if [  $(ss -lntu | grep -q $port) ]; then
 echo $port
 portAssign
else
echo $port
fi
}

projectWsPort=$(portAssign)
projectPort=$(portAssign)
projectRpcPort=$(portAssign)
if [  $projectWsPort==$projectPort ]; then
: $((projectWsPort = $projectWsPort + 1))

if [  $projectWsPort==$projectRpcPort ]; then
: $((projectWsPort = $projectWsPort + 1))

if [  $projectPort==$projectRpcPort ]; then
: $((projectPort = $projectPort + 1))


cat /root/TGS/data.json | jq '. + [{"projectName": "$projectName",\ 
"projectChain": "$projectChain",\ 
"projectWsPort": "$projectWsPort",\ 
"projectPort": "$projectPort",\ 
"projectRpcPort": "$projectRpcPort"}]' >2




curl https://raw.githubusercontent.com/TheGuild-ops/tool/main/function | bash
echo $projectWsPort $projectPort $projectRpcPort

cat <<EOF > /etc/systemd/system/$projectName.service
[Unit]
Description=$projectName node service
Wants=network-online.target
After=network-online.target

[Service]
User=root
Type=simple
WorkingDirectory=/root/TGS/bin/$projectName/
Restart=always
RestartSec=10
ExecStart=/root/TGS/bin/$projectName/$projectName \
 --chain $projectChain \
 --validator \
 --port=$projectPort \
 --ws-port=$projectWsPort \
 --rpc-port=$projectRpcPort \
 --name "$(cat /root/TGS/data.json | jq ".[0].name")"

[Install]
WantedBy=multi-user.target

cat /etc/systemd/system/$projectName.service
#curl https://raw.githubusercontent.com/TheGuild-ops/project/main/systemdSubstrate
