#!/bin/bash

projectName=aleoNode
installPath=/root/TGS
mkdir $installPath/data
mkdir $installPath/data/$projectName/
mkdir $installPath/bin/
mkdir $installPath/data/source 
clear
function portAssign {
port=$((10000 + $RANDOM % 100000))
if [  $(ss -lntu | grep -q $port) ]; then
 echo $port
 portAssign
else
echo $port
fi
}

projectWsPort=$(portAssign)
projectPort=$(portAssign)
projectRpcPort=$(portAssign)

if [  $projectWsPort==$projectPort ]; then
: $((projectWsPort = $projectWsPort + 1))
fi

if [  $projectWsPort==$projectRpcPort ]; then
: $((projectWsPort = $projectWsPort + 1))
fi

if [  $projectPort==$projectRpcPort ]; then
: $((projectPort = $projectPort + 1))
fi

cd /root/TGS/source/
git clone https://github.com/AleoHQ/snarkOS
cd snarkOS
git pull
rustup default nightly
cargo build --release --verbose
sudo mv /root/TGS/source/snarkOS/target/release/snarkos /root/TGS/bin/$projectName

cd $installPath/
git clone https://github.com/AleoHQ/aleo 
cd aleo
cargo install --path .
aleo new >> $installPath/data/$projectName/account.json
cat $installPath/data/$projectName/account.json | grep Address
export ALEO_ADDRESS=$(cat $installPath/data/$projectName/account.json | awk '/Address/ {print $2}')

systemctl stop $projectName

cat <<EOF > /etc/systemd/system/$projectName.service
[Unit]
Description=$projectName node service
Wants=network-online.target
After=network-online.target
[Service]
User=root
Type=simple
WorkingDirectory=/root/TGS/bin/
Restart=always
RestartSec=10
ExecStart=/root/TGS/bin/$projectName --is-miner --miner-address '$ALEO_ADDRESS' --connect 178.166.225.186:4131,135.181.200.109:4131,143.110.237.5:4131,138.201.190.40:4131,64.227.119.195:4131,167.172.34.225:4131,35.242.140.247:4131,34.89.53.207:4131,188.40.185.58:4131,135.181.152.251:4131,94.130.171.118:4131,91.122.52.83:4131,178.18.245.28:4131,78.46.122.47:4131,95.217.9.46:4131,188.40.185.60:4131,135.180.128.248:4131,77.232.40.242:4131,135.181.195.24:4131,95.216.208.150:4131,159.69.119.239:4131,138.201.190.4:4131,95.217.163.88:4131,161.35.22.1:4131,49.12.109.19:4131,91.211.249.166:4131,162.55.43.24:4131,85.114.142.245:4131,135.181.144.152:4131,34.70.100.68:4131,95.216.208.150:4131
Restart=always
LimitNOFILE=10000

[Install]
WantedBy=multi-user.target
EOF


systemctl daemon-reload
systemctl enable $projectName
systemctl start $projectName
